### ISSUE TITLE
adding a registry

### ISSUE THREAD

**Issue by xblox** [uhop/dcl#21]
Hi,
that's not an issue per se but do you have an idea how to support for a sort of class registry? I am trying to get something like dcl.getObject(mid/declaredClass). Right now I can only think patching dcl or monkey patching. 

thanks

**Comment by uhop** [comment]
What exactly is/was required: get a constructor by name? If you have a valid use case, it can be included in the next release.

**Comment by gbaumgart** [comment]
yes, exactly that. A simple static registry in mini.js, so that after each dcl(...) the constructor goes into there, only if props contains "declaredClass". I did it in a fork already: https://github.com/gbaumgart/dcl/blob/master/mini.js#L15

I can think of cases where dcl.clearRegistry() might be also needed, not sure yet.

Thanks for the heads up, Eugene!

**Comment by gbaumgart** [comment]
use case: serialization/deserialization as well server-side mixins from HTML head json fragments. I also run security stuff tied on the class name.

**Comment by uhop** [comment]
Yes, serialization/deserialization is an important use case. I am reopening this issue, as a potential enhancement.

**Comment by uhop** [comment]
2.0 provides an internal hook to create a registry. It could be addressed as an opt-in feature.
